version: '3.9'
services:
  service-order:
    build: .
    ports:
      - "${ORDER_PORT}:${LOCALHOST}"
    environment:
      - PORT=${LOCALHOST}
      - KAFKA_BROKERS=kafka:${KAFKA_CLIENT_PORT}
      - KAFKA_ORDER_TOPIC=${TOPIC_NAME}
    networks:
      - infrastructure_default

networks:
  infrastructure_default:
    external: true
